### ISSUE TITLE
微信网页授权assigns结果为空

### ISSUE THREAD

**Issue by zouh** [h1u2i3/ex_wechat#16]
单微信应用 conn.assigns[:wechat_result] 返回值一直是空

**Comment by h1u2i3** [comment]
1. 用户用微信`首次`访问的时候( `session`不包含 `openid` 的值)，是可以取到正常的返回值的。
2. `Wechat.Plugs.WechatWebsite` 的 `call` 函数中有一个对当前 `session` 中是否有 `openid` 的检测
因此如果`session` 中存在 `openid` 则不做任何处理。
```elixir
  def call(conn, options) do
    if conn |> fetch_session |> get_session(:openid) do
      conn
    else
      case conn do
        ...
      end
    end
  end
```

**Comment by zouh** [comment]
好的，谢谢！没仔细看代码
